### ISSUE TITLE
1- Task1- API upload/download

### ISSUE THREAD

**Issue by ChahidAbderrazak** [ChahidAbderrazak/Synology-data-transfer#1]
### Task1 progress :
- [ ] **send_data (src_folder)**: it uploads all the src_folder (with all  its subfolders and files )  into the DSM  
- [ ]  **download_data (src_folder, dest_folder)**: it downloads the src_folder from the DSM into a local path dest_folder

Hint: 

> The API should work via the internet, not the local network.  we need to make sure that the data are secure by not using any third-party packages but only using the official API request ( API provided by Synology ). Please refer to the official API guide from Synology: https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf

**Comment by TirthPatel3** [comment]
For send_data(src_folder): uploads all the files but does not create subfolder into the DSM.
For download_data(src_folder, dest_folder): downloads a single file from DSM into the local path dest_folder.
